name = "kuroneko-tracker-feed"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-01-13"
account_id = "9c06fda7643a430591cf56d434d1837f"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[vars]
BASE_URL = "http://shizuka.dns.ggrel.net:8787"
KURONEKO_KEY = "22e2858b308cee5181c3e05ca7dd3082"
KURONEKO_NUMBER00 = "1"
KURONEKO_URL = "http://search.kuronekoyamato.co.jp/google/tnekog"
VERSION = "1.0.0"
