name = "kuroneko-tracker-feed"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-01-13"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[vars]
BASE_URL = "https://kuroneko-tracker-feed.rokoucha.workers.dev"
KURONEKO_URL = "https://toi.kuronekoyamato.co.jp/cgi-bin/tneko"
VERSION = "2.0.0"
